# Basic Gates Provided by Qiskit

- #### Hands-on Experiential Learning <font color="red">for the Software Engineer</font>

![](img/Qiskit_Banner_BasicGates.png "")

<BR>

#### <font color="red">Materials Inspiration and Author(s)</font>: 

> **<font color="blue">USAF Research Laboratory</font>**
> - Introduction to Coding Quantum Algorithms: **A Tutorial Series Using Qiskit** : https://arxiv.org/pdf/1903.04359
> - <a href="Basic Gates Provided by Qiskit.ipynb" target="_blank"><font color="blue">Basic Gates Provided by Qiskit</font></a> **(Enhanced)**

<BR>
    
> This JNB introduces the user to some of the predefined gates that come standard with the $\textrm{QuantumCircuit}$ class.  
- Each gate will be presented, accompanied with a short explanation and working example, and a visualization using Qiskit's $\textrm{circuit_drawing}$ tool.  


> For the complete list of standard gates, see: https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/extensions/standard

In [1]:
!pip install qiskit

Processing c:\users\aaron\appdata\local\pip\cache\wheels\29\dd\b2\1fe1a9ac92aaf75b267d893ae27329ea229f292a293017afc7\qiskit-0.31.0-py3-none-any.whl
  Using cached qiskit_aqua-0.9.5-py3-none-any.whl (2.1 MB)


In [45]:
!pip install qiskit[visualization]

  Created wheel for pylatexenc: filename=pylatexenc-2.10-py3-none-any.whl size=136829 sha256=9450aecb1f662d8723eb73461f475303bd05c0285a1b1b04d5f5977714471323
  Stored in directory: c:\users\aaron\appdata\local\pip\cache\wheels\f1\8a\f5\33ee79d4473eb201b519fa40f989b842e373237395a3421f52
Successfully built pylatexenc


In [82]:
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from qiskit.tools.visualization import circuit_drawer
q = QuantumRegister(1)
c = ClassicalRegister(1)
qc = QuantumCircuit(q, c)
qc.h(q)
qc.measure(q, c)
qc.draw(output='text', style={'backgroundcolor': '#EEEEEE'})
#qc.draw(output='mpl', style={'backgroundcolor': '#EEEEEE'})
#qc.draw(output='latex', style={'backgroundcolor': '#EEEEEE'})
#qc.draw(output='latex_source', style={'backgroundcolor': '#EEEEEE'})

┌───┐┌─┐
q678_0: ┤ H ├┤M├
        └───┘└╥┘
  c8: 1/══════╩═
              0

In [6]:
!pip install matplotlib
import matplotlib
from qiskit import ClassicalRegister, QuantumRegister, QuantumCircuit, Aer, execute
from qiskit.tools.visualization import circuit_drawer
import Our_Qiskit_Functions as oq
import math as m
S_simulator = Aer.backends(name='statevector_simulator')[0]
M_simulator = Aer.backends(name='qasm_simulator')[0]

# Single Qubit Gates
-------



## The Identity Operator:  ( <font color="red">I</font> )


<BR>
<font color="blue" size=4>

$$
\begin{bmatrix} 
1 & 0\\ 
0 & 1
\end{bmatrix}
$$

</font>
<BR>
    
The effect of this gate renders the qubit's state unchanged.  An Identity gate does not get any symbol in a circuit diagram.


In [56]:
q = QuantumRegister(1,name='q')
I_qc = QuantumCircuit(q,name='qc')
I_qc.id(q[0])
#I_qc.iden( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(I_qc))
I_qc.id(q[0])
#I_qc.iden( q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(I_qc))

#circuit_drawer(I_qc)
I_qc.draw(output="text")

  __ Initial __ 
1.0  |0>   

  __ Final __ 
1.0  |0>   


┌───┐┌───┐
q_0: ┤ I ├┤ I ├
     └───┘└───┘

## Hadamard ( <font color="red">H</font> )

<BR>
<font color="blue" size=4>
    
$$
\begin{bmatrix} 
1 & 1\\ 
1 & -1
\end{bmatrix}
$$

</font>
<BR>
    
The effect of this gate is as follows:

<BR>

This gate results in a qubit being in a 50 / 50 superposition of states |$0\rangle$ and |$1\rangle$.  While this may seem simple enough, the importance of the Hadamard gate cannot be understated.  In the coming lessons, we shall see that the Hadamard gate is largely responsible for the success of many quantum algorithms.

<BR><BR>

In [58]:
q = QuantumRegister(1,name='q')
H_qc = QuantumCircuit(q,name='qc')


H_qc.id( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(H_qc))

H_qc.h( q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(H_qc))

#circuit_drawer(H_qc)
H_qc.draw(output="text")

  __ Initial __ 
1.0  |0>   

  __ Final __ 
0.70711  |0>   0.70711  |1>   


┌───┐┌───┐
q_0: ┤ I ├┤ H ├
     └───┘└───┘

# Pauli Operators
------

## ( <font color="red">X</font> )

<BR>
<font color="blue" size=4>
    
$$
\begin{bmatrix} 
0 & 1\\ 
1 & 0
\end{bmatrix}
$$

</font>
<BR>
    
The effect of this gate is to flip a qubit's state between |0$\rangle$ and |1$\rangle$.  This gate can be thought of the quantum analog to flipping a classical bit (the NOT gate).  In systems with many superposition states, this gate will be very useful in isolating particular states for future operations.

<BR><BR>

In [59]:
q = QuantumRegister(1,name='q')
X_qc = QuantumCircuit(q,name='qc')

X_qc.id( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(X_qc))

X_qc.x( q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(X_qc))

# circuit_drawer(X_qc)
X_qc.draw(output="text")

  __ Initial __ 
1.0  |0>   

  __ Final __ 
1.0  |1>   


┌───┐┌───┐
q_0: ┤ I ├┤ X ├
     └───┘└───┘

---
## ( <font color="red">Y</font> )

<BR>
<font color="blue" size=4>
    
$$
\begin{bmatrix} 
0 & -i\\ 
i & 0
\end{bmatrix}
$$

</font>
<BR>



The effect of this gate is to flip a qubit's |0$\rangle$ and |1$\rangle$ amplitudes and multiplys by an imaginary number (phase).  From a probabilities perspective, this gate has the same effect as the X gate.  However, the additional phase makes this gate very useful in creating certain constructive / deconstructive interferences.

<BR><BR>

In [60]:
q = QuantumRegister(1,name='q')
Y_qc = QuantumCircuit(q,name='qc')

Y_qc.id( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(Y_qc))

Y_qc.y( q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(Y_qc))

# circuit_drawer(Y_qc)
Y_qc.draw(output="text")

  __ Initial __ 
1.0  |0>   

  __ Final __ 
1.0j |1>   


┌───┐┌───┐
q_0: ┤ I ├┤ Y ├
     └───┘└───┘

---
## ( <font color="red">Z</font> )

<BR>
<font color="blue" size=4>
    
$$
\begin{bmatrix} 
1 & 0\\ 
0 & -1
\end{bmatrix}
$$

</font>
<BR>


The effect of this gate leaves a qubit's |0$\rangle$ amplitude unchanged, while multiplying by -1 (phase) to a qubit's |1$\rangle$ amplitude.  The power of this gate comes from the fact that it only affects the |$1\rangle$ component, which will be frequently used for picking out certain states in the system while leaving others unaltered.

<BR><BR>

In [61]:
q = QuantumRegister(1,name='q')
Z_qc = QuantumCircuit(q,name='qc')

Z_qc.h( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(Z_qc))

Z_qc.z( q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(Z_qc))

# circuit_drawer(Z_qc)
Z_qc.draw(output="text")

  __ Initial __ 
0.70711  |0>   0.70711  |1>   

  __ Final __ 
0.70711  |0>   -0.70711  |1>   


┌───┐┌───┐
q_0: ┤ H ├┤ Z ├
     └───┘└───┘

# Phase Gates
------
The following series of gates are all single qubit operations, which multiply a qubit's |$1\rangle$ state component by a phase.  Doing so does not change the probability of the system, but is an essential component for algorithms that rely on particular kinds of interference.


## PHASE ( <font color="red">R$_{\phi}$</font> )

<BR>
<font color="blue" size=4>
    
$$
\begin{bmatrix} 
1 & 0\\ 
0 & e^{i\phi}
\end{bmatrix}
$$

</font>

<BR>

A gate similar to the Z gate.  It leaves a qubit's |0$\rangle$ amplitude unchanged, while multiplying by a phase $e^{i\phi}$ to a qubit's |1$\rangle$ amplitude.  In Qiskit, this gate goes by the name '$U_1$'.  This gate will find many of the same uses as the Z gate, picking out certain states while leaving others unchanged.  However, the extra degree of phase is a powerful tool for creating certain interference effects.

<BR><BR>

In [62]:
q = QuantumRegister(1,name='q')
u1_qc = QuantumCircuit(q,name='qc')

u1_qc.h( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(u1_qc))

u1_qc.u1( m.pi/4, q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(u1_qc))

# circuit_drawer(u1_qc)
u1_qc.draw(output="text")

  __ Initial __ 
0.70711  |0>   0.70711  |1>   

  __ Final __ 
0.70711  |0>   0.5+0.5j |1>   


┌───┐┌─────────┐
q_0: ┤ H ├┤ U1(π/4) ├
     └───┘└─────────┘

---
## ( <font color="red">S</font> )


<BR>
<font color="blue" size=4>
    
$$
\begin{bmatrix} 
1 & 0\\ 
0 & i
\end{bmatrix}
$$

</font>

<BR>

A pre-defined gate for R$_{\phi}$, $\phi$=$\frac{\pi}{2}$.  It leaves a qubit's |0$\rangle$ amplitude unchanged, while multiplying by i (phase) to a qubit's |1$\rangle$ amplitude.

<BR><BR>

In [64]:
q = QuantumRegister(1,name='q')
S_qc = QuantumCircuit(q,name='qc')

S_qc.h( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(S_qc))

S_qc.s( q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(S_qc))

# circuit_drawer(S_qc)
S_qc.draw(output="text")

  __ Initial __ 
0.70711  |0>   0.70711  |1>   

  __ Final __ 
0.70711  |0>   0.70711j |1>   


┌───┐┌───┐
q_0: ┤ H ├┤ S ├
     └───┘└───┘

---
## ( <font color="red">T</font> )

<BR>
    
A pre-defined gate for <font color="black" size=4> R$_{\phi}$,  $\phi$=$\frac{\pi}{4}$ </font>


<BR>
<font color="blue"  size=4>
    
    
$$
\begin{bmatrix} 
1 & 0\\ 
0 & e^{i\frac{\pi}{4}}
\end{bmatrix}
$$

</font>
<BR>


A pre-defined gate for <font color="black" size=4> R$_{\phi}$, $\phi$=$\frac{\pi}{2}$ </font>.  

<BR>
    
It leaves a qubit's **|0$\rangle$** amplitude unchanged, while multiplying by **i (phase)** to a qubit's **|1$\rangle$** amplitude.

<BR><BR>

In [66]:
q = QuantumRegister(1,name='q')
T_qc = QuantumCircuit(q,name='qc')

T_qc.h( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(T_qc))

T_qc.t( q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(T_qc))

# circuit_drawer(T_qc)
T_qc.draw(output="text")

  __ Initial __ 
0.70711  |0>   0.70711  |1>   

  __ Final __ 
0.70711  |0>   0.5+0.5j |1>   


┌───┐┌───┐
q_0: ┤ H ├┤ T ├
     └───┘└───┘

# Rotation Gates
-------

The follow gates all represent rotations of a state on a Bloch Sphere.  A Bloch sphere is a visual representation that maps the state of a qubit to a location on the surface of a sphere, radius = 1.  An image of a Bloch sphere and it's axes is given below:

<BR><BR>

![title](QA_Images/Les3_Bloch.png)

<BR>

Note that the opposite ends of the **x** and **y** axis are: 


<BR>
<font color="blue" size=4>
    
-x = $\frac{1}{\sqrt{2}} \big{(}$ |$\hspace{.06cm} 0\rangle$ - |$\hspace{.06cm} 1\rangle$ $\big{)}$ $\hspace{.3cm}$
-y = $\frac{1}{\sqrt{2}} \big{(}$ |$\hspace{.06cm} 0\rangle$ - $i\hspace{.05cm}$|$\hspace{.06cm} 1 \rangle$ $\big{)}$

</font>
<BR>

Thus, opposite axes on a Bloch Sphere represent orthogonal states.


## R<font color="blue">$_x$</font>(<font color="red">$\theta$</font>) 


<BR>
<font color="blue" size=4>
    
    
$$
\begin{bmatrix} 
cos(\frac{\theta}{2}) & -i \cdot sin(\frac{\theta}{2})\\ 
-i \cdot sin(\frac{\theta}{2}) & cos(\frac{\theta}{2})
\end{bmatrix}
$$


</font>
<BR>
    
A rotation gate where the initial and final states can be represented as $\theta$ rotation around the x-axis on a Bloch Sphere.

<BR><BR>

In [67]:
q = QuantumRegister(1,name='q')
Rx_qc = QuantumCircuit(q,name='qc')

Rx_qc.id( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(Rx_qc))

Rx_qc.rx( m.pi/2, q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(Rx_qc))

# circuit_drawer(Rx_qc)
Rx_qc.draw(output="text")

  __ Initial __ 
1.0  |0>   

  __ Final __ 
0.70711  |0>   -0.70711j |1>   


┌───┐┌─────────┐
q_0: ┤ I ├┤ Rx(π/2) ├
     └───┘└─────────┘

---
## R<font color="blue">$_y$</font>(<font color="red">$\theta$</font>) 


<BR>
<font color="blue" size=4>
    
    
$$
\begin{bmatrix} 
cos(\frac{\theta}{2}) & -sin(\frac{\theta}{2})\\ 
sin(\frac{\theta}{2}) & cos(\frac{\theta}{2})
\end{bmatrix}
$$


</font>

<BR>
    
    
A rotation gate where the initial and final states can be represented as $\theta$ rotation around the y-axis on a Bloch Sphere.

<BR><BR>

In [68]:
q = QuantumRegister(1,name='q')
Ry_qc = QuantumCircuit(q,name='qc')

Ry_qc.id( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(Ry_qc))

Ry_qc.ry( m.pi/2, q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(Ry_qc))

# circuit_drawer(Ry_qc)
Ry_qc.draw(output="text")

  __ Initial __ 
1.0  |0>   

  __ Final __ 
0.70711  |0>   0.70711  |1>   


┌───┐┌─────────┐
q_0: ┤ I ├┤ Ry(π/2) ├
     └───┘└─────────┘

---
## R<font color="blue">$_z$</font>(<font color="red">$\theta$</font>) 


<BR>
<font color="blue"  size=4>
    
    
$$
\begin{bmatrix} 
e^{\frac{-i\theta}{2}} & 0\\ 
0 & e^{\frac{i\theta}{2}}
\end{bmatrix}
$$

</font>
<BR>


A rotation gate where the initial and final states can be represented as $\theta$ rotation around the z-axis on a Bloch Sphere.

<BR><BR>

In [69]:
q = QuantumRegister(1,name='q')
Rz_qc = QuantumCircuit(q,name='qc')

Rz_qc.h( q[0] )
print('  __ Initial __ ')
print(oq.Wavefunction(Rz_qc))

Rz_qc.rz( m.pi/2, q[0] )
print('\n  __ Final __ ')
print(oq.Wavefunction(Rz_qc))

# circuit_drawer(Rz_qc)
Rz_qc.draw(output="text")

  __ Initial __ 
0.70711  |0>   0.70711  |1>   

  __ Final __ 
0.5-0.5j |0>   0.5+0.5j |1>   


┌───┐┌─────────┐
q_0: ┤ H ├┤ Rz(π/2) ├
     └───┘└─────────┘

# Two Qubit Control Gates
---------

All of the following gates act on 2 qubits.  In particular, each gate uses a 'target qubit' and a 'control qubit'.  The role of the control qubit is to determine whether or not a particular operation is applied to the target qubit.  If the control qubit is in the state |$1\rangle$, then the operation is carried out on the target qubit.  Conversely, if the control qubit is in the state |$0\rangle$, then the target qubit remains unchanged.

## CNOT

The effect of the CNOT gate can be described as follows:

<BR>
<font color="blue"  size=4>
    
$$\textbf{CNOT} \hspace{.2cm} |\hspace{.05cm}00\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}00\rangle $$
$$\textbf{CNOT} \hspace{.2cm} |\hspace{.05cm}01\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}01\rangle $$
$$\textbf{CNOT} \hspace{.2cm} |\hspace{.05cm}10\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}11\rangle $$
$$\textbf{CNOT} \hspace{.2cm} |\hspace{.05cm}11\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}10\rangle $$

<BR><BR>


$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 1 & 0\\ 
\end{bmatrix}
$$

</font>
<BR>

In this notation, the first qubit is the control and the second qubit is the target.  Another way to think of this gate is as a 'control-X' gate, where the state of the control qubit determines whether or not an X gate is applied to the target qubit.  In Qiskit, this gate goes by the name 'CX'.

The CNOT gate is perhaps one of the most important tools in our quantum computing arsenal.  Since we cannot have a purely 'NOT', the CNOT gate is our closest match.  In combination with other gates, it will allow us to construct all manners of multi-qubit operations.

<BR><BR>

In [70]:
q = QuantumRegister(2,name='q')
Cx_qc = QuantumCircuit(q,name='qc')

Cx_qc.h( q[0] )
Cx_qc.id( q[1] )
print('  __ Initial __ ')
print(oq.Wavefunction(Cx_qc))

Cx_qc.cx( q[0], q[1] )
print('\n  __ Final __ ')
print(oq.Wavefunction(Cx_qc))

# circuit_drawer(Cx_qc)
Cx_qc.draw(output="text")

  __ Initial __ 
0.70711  |00>   0.70711  |10>   

  __ Final __ 
0.70711  |00>   0.70711  |11>   


┌───┐     
q_0: ┤ H ├──■──
     ├───┤┌─┴─┐
q_1: ┤ I ├┤ X ├
     └───┘└───┘

In [71]:
q = QuantumRegister(2,name='q')
Cx_qc = QuantumCircuit(q,name='qc')

Cx_qc.h( q[0] )
Cx_qc.cx( q[0], q[1] )
Cx_qc.x( q[0] )
Cx_qc.z( q[1] )
print('  __ Initial __ ')
print(oq.Wavefunction(Cx_qc))

print('\n  __ Final __ ')
print(oq.Wavefunction(Cx_qc))

# circuit_drawer(Cx_qc)
Cx_qc.draw(output="text")

  __ Initial __ 
0.70711  |10>   -0.70711  |01>   

  __ Final __ 
0.70711  |10>   -0.70711  |01>   


┌───┐     ┌───┐
q_0: ┤ H ├──■──┤ X ├
     └───┘┌─┴─┐├───┤
q_1: ─────┤ X ├┤ Z ├
          └───┘└───┘

---
## CZ (Control-Z)

<BR>
    
The control-Z gate works similarly to the CNOT gate, only instead of flipping the target qubit (applying an X gate), we apply a Z gate:

<BR><BR>
<font color="blue"  size=4>
    
$$\textbf{CZ} \hspace{.2cm} |\hspace{.05cm}00\rangle \hspace{.45cm} \rightarrow \hspace{.45cm} |\hspace{.05cm}00\rangle $$
$$\textbf{CZ} \hspace{.2cm} |\hspace{.05cm}01\rangle \hspace{.45cm} \rightarrow \hspace{.45cm} |\hspace{.05cm}01\rangle $$
$$\textbf{CZ} \hspace{.2cm} |\hspace{.05cm}10\rangle \hspace{.45cm} \rightarrow \hspace{.45cm} |\hspace{.05cm}10\rangle $$
$$\textbf{CZ} \hspace{.2cm} |\hspace{.05cm}11\rangle \hspace{.45cm} \rightarrow \hspace{.15cm} -|\hspace{.05cm}11\rangle $$

<BR><BR>


$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & -1\\ 
\end{bmatrix}
$$


</font>

<BR>

Recall that a Z gates leaves a qubit in the state |$0\rangle$ untouched, while flipping the sign on a qubit in the state |$1\rangle$.  Thus, the CZ gate performs a similar operation, only affecting the state |$11\rangle$, as shown above.

<BR><BR>

In [73]:
q = QuantumRegister(2,name='q')
Cz_qc = QuantumCircuit(q,name='qc')

Cz_qc.h( q[0] )
Cz_qc.x( q[1] )
print('  __ Initial __ ')
print(oq.Wavefunction(Cz_qc))

Cz_qc.cz( q[0], q[1] )
print('\n  __ Final __ ')
print(oq.Wavefunction(Cz_qc))

# circuit_drawer(Cz_qc)
Cz_qc.draw(output="text")

  __ Initial __ 
0.70711  |01>   0.70711  |11>   

  __ Final __ 
0.70711  |01>   -0.70711  |11>   


┌───┐   
q_0: ┤ H ├─■─
     ├───┤ │ 
q_1: ┤ X ├─■─
     └───┘

---
## Control Phase Gate

<BR>
    
The control-phase gate, also referred to as a CPHASE gate, uses a control qubit to apply a $R_{\phi}$ gate to a target qubit.  The net effect is similar to that of the control-Z gate, only differing by the phase that gets multiplied to the state **|$11\rangle$**:


<BR><BR>
<font color="blue"  size=4>
    
    
$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & e^{i\phi}\\ 
\end{bmatrix}
$$

</font>
<BR>

In qiskit, this gate goes by the name $CU_1$:

<BR><BR>

In [76]:
q = QuantumRegister(2,name='q')
cu1_qc = QuantumCircuit(q,name='qc')

cu1_qc.x( q[0] )
cu1_qc.h( q[1] )
cu1_qc.id( q[1] )
print('  __ Initial __ ')
print(oq.Wavefunction(cu1_qc))

cu1_qc.cu1( m.pi/2, q[0], q[1] )
print('\n  __ Final __ ')
print(oq.Wavefunction(cu1_qc))

# circuit_drawer(cu1_qc)
cu1_qc.draw(output="text")

  __ Initial __ 
0.70711  |10>   0.70711  |11>   

  __ Final __ 
0.70711  |10>   0.70711j |11>   


Z:\anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: The QuantumCircuit.cu1 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You should use the QuantumCircuit.cp method instead, which acts identically.
  # Remove the CWD from sys.path while we load stuff.


┌───┐               
q_0: ┤ X ├──────■────────
     ├───┤┌───┐ │U1(π/2) 
q_1: ┤ H ├┤ I ├─■────────
     └───┘└───┘

---
## SWAP

The SWAP gate causes two qubits to trade states.

<BR><BR>
<font color="blue"  size=4>
    
    
$$\textbf{SWAP} \hspace{.2cm} |\hspace{.05cm}00\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}00\rangle $$
$$\textbf{SWAP} \hspace{.2cm} |\hspace{.05cm}01\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}10\rangle $$
$$\textbf{SWAP} \hspace{.2cm} |\hspace{.05cm}10\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}01\rangle $$
$$\textbf{SWAP} \hspace{.2cm} |\hspace{.05cm}11\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}11\rangle $$

<BR><BR>

$$
\begin{bmatrix} 
1 & 0 & 0 & 0\\ 
0 & 0 & 1 & 0\\ 
0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$

</font>
<BR>

A simple way of viewing the effect of this gate is that all of the $0$'s and $1$'s in each state switch places.  As a result, we can see that the SWAP gate has no effect on the states |$00\rangle$ and |$11\rangle$.

<BR><BR>

In [78]:
q = QuantumRegister(2,name='q')
swap_qc = QuantumCircuit(q,name='qc')

swap_qc.x( q[0] )
swap_qc.h( q[1] )
swap_qc.id( q[1] )
print('  __ Initial __ ')
print(oq.Wavefunction(swap_qc))

swap_qc.swap( q[0], q[1] )
print('\n  __ Final __ ')
print(oq.Wavefunction(swap_qc))

# circuit_drawer(swap_qc)
swap_qc.draw(output="text")

  __ Initial __ 
0.70711  |10>   0.70711  |11>   

  __ Final __ 
0.70711  |01>   0.70711  |11>   


┌───┐        
q_0: ┤ X ├──────X─
     ├───┤┌───┐ │ 
q_1: ┤ H ├┤ I ├─X─
     └───┘└───┘

# 3 Qubit Control Gates
----

The following two gates take 3 qubits as inputs.  They are essentially higher order versions of the CNOT and SWAP gates, adding one extra control qubit to each.

<BR>
    
## CSWAP

The control-swap gate uses a control qubit to determine whether or not to apply a SWAP gate to two target qubits.  If the control qubit is in the state |$1\rangle$, then a SWAP gate is performed.  Examples:

<BR><BR>
<font color="blue"  size=4>
    
$$\textbf{CSWAP} \hspace{.2cm} |\hspace{.05cm}010\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}010\rangle $$
$$\textbf{CSWAP} \hspace{.2cm} |\hspace{.05cm}101\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}110\rangle $$
$$\textbf{CSWAP} \hspace{.2cm} |\hspace{.05cm}110\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}101\rangle $$
$$\textbf{CSWAP} \hspace{.2cm} |\hspace{.05cm}111\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |\hspace{.05cm}111\rangle $$

<BR><BR>
    
$$
\begin{bmatrix} 
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0\\ 
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\ 
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\ 
\end{bmatrix}
$$


</font>
<BR>
    
This gate is also sometimes referred to as a Fredkin Gate.

<BR><BR>

In [80]:
q = QuantumRegister(3,name='q')
cswap_qc = QuantumCircuit(q,name='qc')

cswap_qc.h( q[0] )
cswap_qc.x( q[1] )
cswap_qc.id( q[2] )
print('  __ Initial __ ')
print(oq.Wavefunction(cswap_qc))

cswap_qc.cswap( q[0], q[1], q[2] )
print('\n  __ Final __ ')
print(oq.Wavefunction(cswap_qc))

# circuit_drawer(cswap_qc)
cswap_qc.draw(output="text")

  __ Initial __ 
0.70711  |010>   0.70711  |110>   

  __ Final __ 
0.70711  |010>   0.70711  |101>   


┌───┐   
q_0: ┤ H ├─■─
     ├───┤ │ 
q_1: ┤ X ├─X─
     ├───┤ │ 
q_2: ┤ I ├─X─
     └───┘

---
## CCNOT

<BR>
The control-control not gate uses two control qubits to determine if an X gate is applied to a single target qubit.  
    
Examples:

<BR>
<font color="blue" size=4>
    
$$\textbf{CCNOT} \hspace{.2cm} |010\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |010\rangle $$
$$\textbf{CCNOT} \hspace{.2cm} |101\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |101\rangle $$
$$\textbf{CCNOT} \hspace{.2cm} |110\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |111\rangle $$
$$\textbf{CCNOT} \hspace{.2cm} |111\rangle \hspace{.25cm} \rightarrow \hspace{.25cm} |110\rangle $$

<BR><BR>

$$
\begin{bmatrix} 
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0\\ 
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0\\ 
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0\\ 
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0\\ 
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0\\ 
\end{bmatrix}
$$


</font>
<BR>
    
    
This gate is also sometimes referred to as a Toffoli Gate.  Much like the CNOT gate, the effect of this gate is equivalent to an X gate on the states |$110\rangle$ and |$111\rangle$.

<BR><BR>

In [81]:
q = QuantumRegister(3,name='q')
ccnot_qc = QuantumCircuit(q,name='qc')

ccnot_qc.x( q[0] )
ccnot_qc.x( q[1] )
ccnot_qc.h( q[2] )
ccnot_qc.z( q[2] )
print('  __ Initial __ ')
print(oq.Wavefunction(ccnot_qc))

ccnot_qc.ccx( q[0], q[1], q[2] )
print('\n  __ Final __ ')
print(oq.Wavefunction(ccnot_qc))

# circuit_drawer(ccnot_qc)
ccnot_qc.draw(output="text")

  __ Initial __ 
0.70711  |110>   -0.70711  |111>   

  __ Final __ 
-0.70711  |110>   0.70711  |111>   


┌───┐          
q_0: ┤ X ├───────■──
     ├───┤       │  
q_1: ┤ X ├───────■──
     ├───┤┌───┐┌─┴─┐
q_2: ┤ H ├┤ Z ├┤ X ├
     └───┘└───┘└───┘

![the-end](img/the-end.png "the-end")